name: GHCR Cleanup

on:
  workflow_dispatch:
#  schedule:
#    - cron: "5 * * * *"  # every hour


jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Delete old untagged versions
        uses: Chizkiyahu/delete-untagged-ghcr-action@v6
        with:
          token: ${{ secrets.GHCR_PAT }}  # Your PAT with delete:packages
          repository_owner: ${{ github.repository_owner }}
          repository: ${{ github.repository }}
          owner_type: org  # 'org' or 'user' if personal
          untagged_only: true
          except_untagged_multiplatform: false  # Crucial: skips parts needed by your tagged multi-arch image

